name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        backend: [numpy]
    name: Run tests
    runs-on: ubuntu-latest
    env:
      PYTHON: ${{ matrix.python-version }}
      KERAS_HOME: .github/workflows/config/${{ matrix.backend }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for changes in keras/src/applications
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            applications:
              - 'keras/src/applications/**'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip setuptools
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: pip cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt --progress-bar off --upgrade
          pip uninstall -y keras keras-nightly
          pip install tf_keras==2.16.0 --progress-bar off --upgrade
          pip install -e "." --progress-bar off --upgrade
      - name: Instrument code
        uses: AryazE/auto-dylin/instrument@main
        with:
            analysis-coverage: false
            exclude-checkers: 'ML-01 ML-02 ML-03 ML-04'
    #   - name: Test applications with pytest
    #     if: ${{ steps.filter.outputs.applications == 'true' }}
    #     run: |
    #       pytest keras/src/applications
      - name: Test integrations
        if: ${{ matrix.backend != 'numpy'}}
        run: |
          python integration_tests/import_test.py
          python integration_tests/numerical_test.py
      - name: Test TF-specific integrations
        if: ${{ matrix.backend == 'tensorflow'}}
        run: |
          python integration_tests/tf_distribute_training_test.py
      - name: Test Torch-specific integrations
        if: ${{ matrix.backend == 'torch'}}
        run: |
          pytest integration_tests/torch_workflow_test.py
      - name: Test with pytest
        run: |
          pytest -n 4 keras --ignore keras/src/applications
      - name: Report results
        if: always()
        uses: AryazE/auto-dylin/report@main